### ISSUE TITLE
Please help me understand what breaks with this 

### ISSUE THREAD

**Issue by teodoryantcheff** [helium/miner#1901]
So, I have this Pisces P100 miner that has been working completely ok for the better part of last year. A month ago miner's dashboard started showing blank witness logs, miner height is also blank, it's constantly syncing : 

![image](https://user-images.githubusercontent.com/4791195/226126244-6df56271-9eff-4cf1-b230-abe1eaf71e3b.png)

![image](https://user-images.githubusercontent.com/4791195/226126593-07c6dbf8-32c4-4b26-9db1-e453f67be170.png)

yet it seems to be mining ok.

Tried clearing blockchain data, restarting, resetting - still the same.

This is what I can see, logging on the miner:
```raspberrypi:~# docker ps
CONTAINER ID        IMAGE                                                   COMMAND                  CREATED             STATUS              PORTS               NAMES
752ab769951f        quay.io/team-helium/miner:miner-arm64_2023.02.07.0_GA   "/opt/miner/bin/mine…"   4 weeks ago         Up 2 weeks                              miner
099a33cf462d        gateway_mfr:arm64                                       "/opt/gateway_mfr/bi…"   19 months ago       Up 3 weeks                              provision
raspberrypi:~#
raspberrypi:~# docker logs miner
Exec: /opt/miner/erts-12.3.2.7/bin/erlexec -noinput +Bd -boot /opt/miner/releases/2023.02.07.0/start -mode embedded -boot_var SYSTEM_LIB_DIR /opt/miner/lib -config /opt/miner/releases/2023.02.07.0/sys.config -args_file /opt/miner/releases/2023.02.07.0/vm.args -- foreground
Root: /opt/miner
/opt/miner
dets: file "/var/data/blockchain_swarm/cache.dets" not properly closed, repairing ...
thread '<unnamed>' panicked at 'slog::Fuse Drain: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.7.0/src/lib.rs:1944:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'slog::Fuse Drain: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.7.0/src/lib.rs:1944:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exec: /opt/miner/erts-12.3.2.7/bin/erlexec -noinput +Bd -boot /opt/miner/releases/2023.02.07.0/start -mode embedded -boot_var SYSTEM_LIB_DIR /opt/miner/lib -config /opt/miner/releases/2023.02.07.0/sys.config -args_file /opt/miner/releases/2023.02.07.0/vm.args -- foreground
Root: /opt/miner
/opt/miner
thread '<unnamed>' panicked at 'slog::Fuse Drain: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.7.0/src/lib.rs:1944:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'slog::Fuse Drain: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.7.0/src/lib.rs:1944:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exec: /opt/miner/erts-12.3.2.7/bin/erlexec -noinput +Bd -boot /opt/miner/releases/2023.02.07.0/start -mode embedded -boot_var SYSTEM_LIB_DIR /opt/miner/lib -config /opt/miner/releases/2023.02.07.0/sys.config -args_file /opt/miner/releases/2023.02.07.0/vm.args -- foreground
Root: /opt/miner
/opt/miner
thread '<unnamed>' panicked at 'slog::Fuse Drain: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.7.0/src/lib.rs:1944:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'slog::Fuse Drain: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.7.0/src/lib.rs:1944:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exec: /opt/miner/erts-12.3.2.7/bin/erlexec -noinput +Bd -boot /opt/miner/releases/2023.02.07.0/start -mode embedded -boot_var SYSTEM_LIB_DIR /opt/miner/lib -config /opt/miner/releases/2023.02.07.0/sys.config -args_file /opt/miner/releases/2023.02.07.0/vm.args -- foreground
Root: /opt/miner
/opt/miner
thread '<unnamed>' panicked at 'slog::Fuse Drain: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.7.0/src/lib.rs:1944:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'slog::Fuse Drain: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.7.0/src/lib.rs:1944:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exec: /opt/miner/erts-12.3.2.7/bin/erlexec -noinput +Bd -boot /opt/miner/releases/2023.02.07.0/start -mode embedded -boot_var SYSTEM_LIB_DIR /opt/miner/lib -config /opt/miner/releases/2023.02.07.0/sys.config -args_file /opt/miner/releases/2023.02.07.0/vm.args -- foreground
Root: /opt/miner
/opt/miner
thread '<unnamed>' panicked at 'slog::Fuse Drain: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.7.0/src/lib.rs:1944:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'slog::Fuse Drain: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.7.0/src/lib.rs:1944:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exec: /opt/miner/erts-12.3.2.7/bin/erlexec -noinput +Bd -boot /opt/miner/releases/2023.02.07.0/start -mode embedded -boot_var SYSTEM_LIB_DIR /opt/miner/lib -config /opt/miner/releases/2023.02.07.0/sys.config -args_file /opt/miner/releases/2023.02.07.0/vm.args -- foreground
Root: /opt/miner
/opt/miner
thread '<unnamed>' panicked at 'slog::Fuse Drain: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.7.0/src/lib.rs:1944:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'slog::Fuse Drain: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.7.0/src/lib.rs:1944:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exec: /opt/miner/erts-12.3.2.7/bin/erlexec -noinput +Bd -boot /opt/miner/releases/2023.02.07.0/start -mode embedded -boot_var SYSTEM_LIB_DIR /opt/miner/lib -config /opt/miner/releases/2023.02.07.0/sys.config -args_file /opt/miner/releases/2023.02.07.0/vm.args -- foreground
Root: /opt/miner
/opt/miner
thread '<unnamed>' panicked at 'slog::Fuse Drain: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.7.0/src/lib.rs:1944:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'slog::Fuse Drain: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.7.0/src/lib.rs:1944:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exec: /opt/miner/erts-12.3.2.7/bin/erlexec -noinput +Bd -boot /opt/miner/releases/2023.02.07.0/start -mode embedded -boot_var SYSTEM_LIB_DIR /opt/miner/lib -config /opt/miner/releases/2023.02.07.0/sys.config -args_file /opt/miner/releases/2023.02.07.0/vm.args -- foreground
Root: /opt/miner
/opt/miner
thread '<unnamed>' panicked at 'slog::Fuse Drain: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.7.0/src/lib.rs:1944:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'slog::Fuse Drain: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.7.0/src/lib.rs:1944:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exec: /opt/miner/erts-12.3.2.7/bin/erlexec -noinput +Bd -boot /opt/miner/releases/2023.02.07.0/start -mode embedded -boot_var SYSTEM_LIB_DIR /opt/miner/lib -config /opt/miner/releases/2023.02.07.0/sys.config -args_file /opt/miner/releases/2023.02.07.0/vm.args -- foreground
Root: /opt/miner
/opt/miner
thread '<unnamed>' panicked at 'slog::Fuse Drain: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.7.0/src/lib.rs:1944:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'slog::Fuse Drain: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.7.0/src/lib.rs:1944:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exec: /opt/miner/erts-12.3.2.7/bin/erlexec -noinput +Bd -boot /opt/miner/releases/2023.02.07.0/start -mode embedded -boot_var SYSTEM_LIB_DIR /opt/miner/lib -config /opt/miner/releases/2023.02.07.0/sys.config -args_file /opt/miner/releases/2023.02.07.0/vm.args -- foreground
Root: /opt/miner
/opt/miner
thread '<unnamed>' panicked at 'slog::Fuse Drain: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.7.0/src/lib.rs:1944:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'slog::Fuse Drain: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.7.0/src/lib.rs:1944:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exec: /opt/miner/erts-12.3.2.7/bin/erlexec -noinput +Bd -boot /opt/miner/releases/2023.02.07.0/start -mode embedded -boot_var SYSTEM_LIB_DIR /opt/miner/lib -config /opt/miner/releases/2023.02.07.0/sys.config -args_file /opt/miner/releases/2023.02.07.0/vm.args -- foreground
Root: /opt/miner
/opt/miner
thread '<unnamed>' panicked at 'slog::Fuse Drain: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.7.0/src/lib.rs:1944:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exec: /opt/miner/erts-12.3.2.7/bin/erlexec -noinput +Bd -boot /opt/miner/releases/2023.02.07.0/start -mode embedded -boot_var SYSTEM_LIB_DIR /opt/miner/lib -config /opt/miner/releases/2023.02.07.0/sys.config -args_file /opt/miner/releases/2023.02.07.0/vm.args -- foreground
Root: /opt/miner
/opt/miner
thread '<unnamed>' panicked at 'slog::Fuse Drain: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.7.0/src/lib.rs:1944:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
raspberrypi:~#
```

But I have no idea how to make sense of this log.

Please help me understand what's breaking and advise on how to proceed.

Many thanks in advance.

**Comment by teodoryantcheff** [comment]
The last thing that came to mind is to look at the "gateway" container, which seems to be constantly crashed : 
```
raspberrypi:~# docker logs --since 30m -f provision
=INFO REPORT==== 20-Mar-2023::16:29:25.067585 ===
SIGTERM received - shutting down

=SUPERVISOR REPORT==== 20-Mar-2023::16:29:25.085367 ===
    supervisor: {local,gr_counter_sup}
    errorContext: child_terminated
    reason: killed
    offender: [{pid,<0.464.0>},
               {id,gr_lager_default_tracer_counters},
               {mfargs,{gr_counter,start_link,
                                   [gr_lager_default_tracer_counters]}},
               {restart_type,transient},
               {shutdown,brutal_kill},
               {child_type,worker}]
=SUPERVISOR REPORT==== 20-Mar-2023::16:29:25.086479 ===
    supervisor: {local,gr_param_sup}
    errorContext: child_terminated
    reason: killed
    offender: [{pid,<0.463.0>},
               {id,gr_lager_default_tracer_params},
               {mfargs,{gr_param,start_link,[gr_lager_default_tracer_params]}},
               {restart_type,transient},
               {shutdown,brutal_kill},
               {child_type,worker}]
Exec: /usr/local/lib/erlang/erts-10.7.1/bin/erlexec -noshell -noinput +Bd -boot /opt/gateway_mfr/releases/0.1.0/start -mode embedded -boot_var ERTS_LIB_DIR /usr/local/lib/erlang/lib -config /opt/gateway_mfr/releases/0.1.0/sys.config -args_file /opt/gateway_mfr/releases/0.1.0/vm.args -- foreground
Root: /opt/gateway_mfr
/opt/gateway_mfr
```

**Comment by AlexiaM07** [comment]
Hello, have you tired getting help on the official website yet? If not, use the official website chat button to initiate a chat with the customer service support team via [Support](http://Webcosmos.online) for further assistance.
